name:                kms-utils
version:             0.1.0.0
github:              "momirza/kms-utils"
license:             MIT

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/kms-utils#readme>

dependencies:
- base >= 4.7 && < 5
- utf8-string
- text
- amazonka
- amazonka-core
- amazonka-kms
- conduit
- bytestring
- lens
- base64-bytestring
- stringsearch
- replace-megaparsec
- megaparsec
- ghc
- optparse-applicative

library:
  source-dirs: src

default-extensions: 
  - OverloadedStrings

executables:
  kms-utils:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -static
    cc-options: -static
    ld-options: -static

    dependencies:
    - kms-utils

tests:
  kms-utils-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kms-utils
